# Generated by Django 5.0.1 on 2026-02-15 10:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "max_users",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "max_queries_per_month",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "max_tokens_per_month",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                ("next_payment_date", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SystemAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("tenant_created", "Tenant Created"),
                            ("tenant_updated", "Tenant Updated"),
                            ("tenant_suspended", "Tenant Suspended"),
                            ("tenant_activated", "Tenant Activated"),
                            ("tenant_deleted", "Tenant Deleted"),
                            ("plan_changed", "Subscription Plan Changed"),
                            ("service_restarted", "Service Restarted"),
                            ("config_updated", "System Configuration Updated"),
                            ("emergency_access_granted", "Emergency Access Granted"),
                            ("emergency_access_revoked", "Emergency Access Revoked"),
                            ("platform_overview_viewed", "Platform Overview Viewed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_affected",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_audit_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "system_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="system_audi_timesta_afdeb8_idx"
                    ),
                    models.Index(
                        fields=["action"], name="system_audi_action_1d8bfe_idx"
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="system_audi_perform_2ad1ff_idx",
                    ),
                    models.Index(
                        fields=["tenant_affected", "-timestamp"],
                        name="system_audi_tenant__3b5c0b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("queries_count", models.IntegerField(default=0)),
                ("failed_queries_count", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("embedding_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("documents_count", models.IntegerField(default=0)),
                ("active_users_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "usage_metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-date"],
                        name="usage_metri_tenant__1d8be8_idx",
                    ),
                    models.Index(fields=["date"], name="usage_metri_date_9a7747_idx"),
                ],
                "unique_together": {("tenant", "date")},
            },
        ),
    ]
