# Generated by Django 5.0.1 on 2026-02-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_subscriptionplan_tenantsubscription_systemauditlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("huggingface", "HuggingFace Inference API"),
                            ("anthropic", "Anthropic"),
                            ("ollama", "Ollama (Local)"),
                        ],
                        default="openai",
                        help_text="Which LLM provider to use for chat responses.",
                        max_length=30,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="gpt-3.5-turbo",
                        help_text="Model identifier, e.g. gpt-4, mistralai/Mistral-7B-Instruct-v0.1, llama3",
                        max_length=200,
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API key for the LLM provider (stored in DB, shown masked in UI).",
                        max_length=500,
                    ),
                ),
                (
                    "llm_api_base",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom API base URL (required for Ollama, optional for HuggingFace endpoints).",
                        max_length=500,
                    ),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("huggingface", "HuggingFace Inference API"),
                            ("sentence_transformers", "Sentence Transformers (Local)"),
                        ],
                        default="openai",
                        help_text="Which provider to use for document/query embeddings.",
                        max_length=30,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        help_text="Embedding model identifier.",
                        max_length=200,
                    ),
                ),
                (
                    "embedding_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API key for the embedding provider (can differ from LLM key).",
                        max_length=500,
                    ),
                ),
                (
                    "embedding_api_base",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom API base URL for the embedding provider.",
                        max_length=500,
                    ),
                ),
                (
                    "max_tokens_per_request",
                    models.IntegerField(
                        default=1000,
                        help_text="Maximum tokens in a single LLM response.",
                    ),
                ),
                (
                    "requests_per_minute",
                    models.IntegerField(
                        default=60, help_text="Global rate limit for LLM requests."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider Configuration",
                "db_table": "ai_provider_config",
            },
        ),
    ]
