# Generated by Django 4.2.18 on 2026-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ai_provider_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
