# Generated by Django 5.0.1 on 2026-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_profile_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("bug", "Bug / Error"),
                    ("feature", "Feature Request"),
                    ("access", "Access Issue"),
                    ("performance", "Performance Problem"),
                    ("data", "Data Issue"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="context_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
