# Generated by Django 5.0.1 on 2026-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_support_category_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiproviderconfig",
            name="llm_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("huggingface", "HuggingFace Inference API"),
                    ("anthropic", "Anthropic"),
                    ("ollama", "Ollama (Local)"),
                    ("local", "Local Transformers (No API key)"),
                ],
                default="openai",
                help_text="Which LLM provider to use for chat responses.",
                max_length=30,
            ),
        ),
    ]
