# Generated by Django 5.0.1 on 2026-03-09 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_tenant_admins_to_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_tenant_admin",
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user_management", "User Management"),
                            ("document", "Document"),
                            ("role", "Role & Permission"),
                            ("department", "Department"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("department", "Department"),
                            ("role", "Role"),
                            ("tenant", "Entire Tenant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        help_text="UUID of the user / department / role / tenant this targets."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="core.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_receipts",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "-created_at"], name="notificatio_tenant__b31a53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="notificatio_target__031211_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationreceipt",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notificatio_user_id_24e1a9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationreceipt",
            unique_together={("notification", "user")},
        ),
    ]
