# Generated by Django 5.0.1 on 2026-03-10 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_user_is_tenant_admin_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clearance_level",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Security clearance 0-5, matches document classification_level.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contractor", "Contractor"),
                    ("intern", "Intern"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hired_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("division", "Division"),
                            ("department", "Department"),
                            ("team", "Team"),
                            ("cost_center", "Cost Center"),
                            ("location", "Location"),
                        ],
                        default="department",
                        max_length=20,
                    ),
                ),
                ("depth", models.PositiveIntegerField(default=0)),
                ("path", models.CharField(blank=True, default="", max_length=1000)),
                ("sibling_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.orgunit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_units",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "org_units",
                "ordering": ["path", "sibling_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnitClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendant_links",
                        to="core.orgunit",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestor_links",
                        to="core.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "org_unit_closure",
            },
        ),
        migrations.CreateModel(
            name="UserOrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("temporary", "Temporary"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.orgunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_org_units",
            },
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["tenant", "unit_type"], name="org_units_tenant__019eb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["tenant", "parent"], name="org_units_tenant__4c6e33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["tenant", "depth"], name="org_units_tenant__368247_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["tenant", "is_active"], name="org_units_tenant__57484d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(fields=["path"], name="org_units_path_870cd2_idx"),
        ),
        migrations.AddConstraint(
            model_name="orgunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("tenant", "code"),
                name="unique_org_unit_code_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="orgunitclosure",
            index=models.Index(
                fields=["ancestor", "depth"], name="org_unit_cl_ancesto_117761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgunitclosure",
            index=models.Index(
                fields=["descendant", "depth"], name="org_unit_cl_descend_0c3c32_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orgunitclosure",
            unique_together={("ancestor", "descendant")},
        ),
        migrations.AddIndex(
            model_name="userorgunit",
            index=models.Index(
                fields=["user", "is_active"], name="user_org_un_user_id_cb7a94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userorgunit",
            index=models.Index(
                fields=["org_unit", "is_active"], name="user_org_un_org_uni_149bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userorgunit",
            index=models.Index(
                fields=["expires_at"], name="user_org_un_expires_06d4c5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userorgunit",
            unique_together={("user", "org_unit")},
        ),
    ]
