# Generated by Django 5.0.1 on 2026-03-11 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auth_identity_redesign"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("default_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feature_flags",
                "ordering": ["key"],
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="billing_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="tenant",
            name="data_region",
            field=models.CharField(
                choices=[
                    ("us-east", "US East"),
                    ("eu-west", "EU West"),
                    ("ap-south", "AP South"),
                ],
                default="us-east",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("configured", "Configured"),
                    ("active", "Active"),
                ],
                default="created",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HealthCheckLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("api_server", "API Server"),
                            ("database", "Database"),
                            ("redis", "Redis"),
                            ("qdrant", "Qdrant"),
                            ("celery", "Celery"),
                            ("llm_provider", "LLM Provider"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "health_check_logs",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["component", "-checked_at"],
                        name="health_chec_compone_a4e804_idx",
                    ),
                    models.Index(
                        fields=["-checked_at"], name="health_chec_checked_553e0d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_min_length", models.IntegerField(default=8)),
                ("password_complexity", models.BooleanField(default=False)),
                (
                    "mfa_enforcement",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=20,
                    ),
                ),
                ("session_timeout_min", models.IntegerField(default=60)),
                ("max_login_attempts", models.IntegerField(default=10)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(default="#6366f1", max_length=7)),
                (
                    "custom_domain",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ai_provider_override", models.JSONField(blank=True, null=True)),
                ("max_tokens_per_request", models.IntegerField(default=1000)),
                ("rag_top_k", models.IntegerField(default=5)),
                ("retention_days", models.IntegerField(default=365)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_configs",
            },
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription_start", "Subscription Start"),
                            ("subscription_renew", "Subscription Renewal"),
                            ("plan_upgrade", "Plan Upgrade"),
                            ("plan_downgrade", "Plan Downgrade"),
                            ("payment_success", "Payment Success"),
                            ("payment_failed", "Payment Failed"),
                            ("invoice_created", "Invoice Created"),
                            ("trial_start", "Trial Start"),
                            ("trial_expired", "Trial Expired"),
                            ("cancellation", "Cancellation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stripe_event_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_events",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "billing_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="billing_eve_tenant__ebd8b6_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="billing_eve_event_t_cb9680_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("pdf_url", models.CharField(blank=True, default="", max_length=512)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="invoices_tenant__3b0a67_idx",
                    ),
                    models.Index(fields=["status"], name="invoices_status_07776b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanFeatureGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_gates",
                        to="core.featureflag",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_gates",
                        to="core.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_feature_gates",
                "unique_together": {("plan", "feature")},
            },
        ),
        migrations.CreateModel(
            name="TenantFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_overrides",
                        to="core.featureflag",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_overrides",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_feature_flags",
                "unique_together": {("tenant", "feature")},
            },
        ),
    ]
