# Generated by Django 5.0.1 on 2026-03-11 17:03

from django.db import migrations


STANDARD_FLAGS = [
    ('advanced_rag', 'Advanced RAG', 'Enable advanced RAG features (multi-doc queries, citations)', True),
    ('document_ocr', 'Document OCR', 'Enable OCR processing for scanned documents', False),
    ('chat_export', 'Chat Export', 'Allow users to export chat sessions', True),
    ('custom_branding', 'Custom Branding', 'Enable tenant-level branding customization', False),
    ('mfa_enforcement', 'MFA Enforcement', 'Allow tenant admins to enforce MFA', True),
    ('api_access', 'API Access', 'Enable external API access for tenants', False),
    ('bulk_upload', 'Bulk Upload', 'Allow bulk document uploads', True),
    ('analytics_dashboard', 'Analytics Dashboard', 'Enable analytics dashboard for tenant admins', True),
    ('audit_log_export', 'Audit Log Export', 'Allow exporting audit logs', False),
    ('priority_support', 'Priority Support', 'Routes support tickets to priority queue', False),
]


def seed_flags(apps, schema_editor):
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    for key, name, description, default_enabled in STANDARD_FLAGS:
        FeatureFlag.objects.get_or_create(
            key=key,
            defaults={
                'name': name,
                'description': description,
                'default_enabled': default_enabled,
                'is_active': True,
            },
        )


def unseed_flags(apps, schema_editor):
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    keys = [k for k, _, _, _ in STANDARD_FLAGS]
    FeatureFlag.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_featureflag_tenant_billing_email_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_flags, unseed_flags),
    ]
