# Generated by Django 5.0.1 on 2026-03-11 17:54

from django.db import migrations


TEMPLATES = [
    {
        'key': 'document_uploaded',
        'title_template': 'Document uploaded',
        'message_template': '{{ user_name }} uploaded "{{ document_name }}" to {{ folder_name }}.',
        'email_subject': 'New document uploaded: {{ document_name }}',
        'email_body': 'Hi {{ recipient_name }},\n\n{{ user_name }} uploaded "{{ document_name }}" to {{ folder_name }}.\n\nView it in your dashboard.',
        'category': 'documents',
        'default_priority': 'normal',
        'default_channels': ['in_app'],
    },
    {
        'key': 'document_shared',
        'title_template': 'Document shared with you',
        'message_template': '{{ user_name }} shared "{{ document_name }}" with you.',
        'email_subject': '{{ user_name }} shared a document with you',
        'email_body': 'Hi {{ recipient_name }},\n\n{{ user_name }} shared "{{ document_name }}" with you.\n\nClick to view the document in your dashboard.',
        'category': 'documents',
        'default_priority': 'normal',
        'default_channels': ['in_app', 'email'],
    },
    {
        'key': 'document_access_revoked',
        'title_template': 'Document access revoked',
        'message_template': 'Your access to "{{ document_name }}" has been revoked.',
        'email_subject': 'Document access revoked',
        'email_body': 'Hi {{ recipient_name }},\n\nYour access to "{{ document_name }}" has been revoked by {{ user_name }}.',
        'category': 'documents',
        'default_priority': 'normal',
        'default_channels': ['in_app'],
    },
    {
        'key': 'chat_response_ready',
        'title_template': 'AI response ready',
        'message_template': 'Your query in "{{ session_name }}" has a new response.',
        'email_subject': 'AI response ready',
        'email_body': '',
        'category': 'chat',
        'default_priority': 'low',
        'default_channels': ['in_app'],
    },
    {
        'key': 'user_created',
        'title_template': 'New user joined',
        'message_template': '{{ user_name }} has joined {{ tenant_name }}.',
        'email_subject': 'New team member: {{ user_name }}',
        'email_body': 'Hi {{ recipient_name }},\n\n{{ user_name }} ({{ user_email }}) has joined {{ tenant_name }}.',
        'category': 'user_management',
        'default_priority': 'low',
        'default_channels': ['in_app'],
    },
    {
        'key': 'user_role_changed',
        'title_template': 'Role updated',
        'message_template': 'Your role has been updated to {{ new_role }}.',
        'email_subject': 'Your role has been updated',
        'email_body': 'Hi {{ recipient_name }},\n\nYour role has been updated from {{ old_role }} to {{ new_role }} by {{ admin_name }}.',
        'category': 'user_management',
        'default_priority': 'normal',
        'default_channels': ['in_app', 'email'],
    },
    {
        'key': 'password_changed',
        'title_template': 'Password changed',
        'message_template': 'Your password was changed successfully.',
        'email_subject': 'Your password has been changed',
        'email_body': 'Hi {{ recipient_name }},\n\nYour password was changed. If you did not do this, contact your administrator immediately.',
        'category': 'security',
        'default_priority': 'high',
        'default_channels': ['in_app', 'email'],
    },
    {
        'key': 'login_suspicious',
        'title_template': 'Suspicious login detected',
        'message_template': 'A login from {{ ip_address }} ({{ location }}) was detected on your account.',
        'email_subject': 'Suspicious login on your account',
        'email_body': 'Hi {{ recipient_name }},\n\nA login from {{ ip_address }} ({{ location }}) was detected at {{ login_time }}.\n\nIf this was not you, change your password immediately.',
        'category': 'security',
        'default_priority': 'urgent',
        'default_channels': ['in_app', 'email'],
    },
    {
        'key': 'system_maintenance',
        'title_template': 'Scheduled maintenance',
        'message_template': 'System maintenance scheduled for {{ maintenance_date }}. Expected downtime: {{ duration }}.',
        'email_subject': 'Scheduled maintenance: {{ maintenance_date }}',
        'email_body': 'Hi {{ recipient_name }},\n\nScheduled maintenance will occur on {{ maintenance_date }}.\nExpected downtime: {{ duration }}.\n\nPlease save your work before the maintenance window.',
        'category': 'system',
        'default_priority': 'high',
        'default_channels': ['in_app', 'email'],
    },
    {
        'key': 'admin_broadcast',
        'title_template': '{{ title }}',
        'message_template': '{{ message }}',
        'email_subject': '{{ title }}',
        'email_body': '{{ message }}',
        'category': 'admin',
        'default_priority': 'normal',
        'default_channels': ['in_app'],
    },
]


def seed_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('core', 'NotificationTemplate')
    for tpl in TEMPLATES:
        NotificationTemplate.objects.update_or_create(
            key=tpl['key'],
            defaults=tpl,
        )


def unseed_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('core', 'NotificationTemplate')
    keys = [t['key'] for t in TEMPLATES]
    NotificationTemplate.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_notification_v2_models"),
    ]

    operations = [
        migrations.RunPython(seed_templates, unseed_templates),
    ]
