# Generated by Django 5.0.1 on 2026-03-12 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_seed_notification_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditRetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("retention_class", models.CharField(max_length=20)),
                ("retention_days", models.IntegerField()),
                (
                    "archive_to",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_policies",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_retention_policies",
                "ordering": ["retention_class"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processing_purpose", models.CharField(max_length=200)),
                ("data_categories", models.JSONField(default=list)),
                ("data_subjects", models.CharField(max_length=100)),
                ("recipients", models.JSONField(default=list)),
                ("retention_period", models.CharField(max_length=100)),
                ("legal_basis", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("platform", "Platform"),
                            ("system", "System"),
                        ],
                        default="tenant",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("query", "Query"),
                            ("grant_access", "Grant Access"),
                            ("revoke_access", "Revoke Access"),
                            ("config_change", "Config Change"),
                            ("export", "Export"),
                            ("mfa_event", "MFA Event"),
                            ("password_change", "Password Change"),
                            ("session_event", "Session Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("endpoint", models.CharField(blank=True, default="", max_length=500)),
                (
                    "http_method",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("denied", "Denied"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automated", "Automated"),
                            ("system", "System"),
                            ("schedule", "Scheduled"),
                        ],
                        default="manual",
                        max_length=15,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("regulation_tags", models.JSONField(blank=True, default=list)),
                (
                    "data_classification",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "retention_class",
                    models.CharField(default="standard", max_length=20),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-timestamp"],
                        name="audit_event_tenant__6b6279_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_event_user_id_36e2e1_idx",
                    ),
                    models.Index(
                        fields=["scope", "-timestamp"],
                        name="audit_event_scope_378382_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_event_action_39022f_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_event_resourc_917803_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="audit_event_request_3a79d3_idx"
                    ),
                    models.Index(
                        fields=["outcome", "-timestamp"],
                        name="audit_event_outcome_11f083_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataDeletionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_scope", models.JSONField(default=dict)),
                ("legal_basis", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("deletion_proof", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "data_deletion_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="data_deleti_tenant__fdbe7d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_key", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("source_events", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_alerts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "security_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="security_al_tenant__b19cd0_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="security_al_severit_1b3239_idx",
                    ),
                    models.Index(
                        fields=["rule_key", "-created_at"],
                        name="security_al_rule_ke_9f7747_idx",
                    ),
                ],
            },
        ),
    ]
