# Generated by Django 5.0.1 on 2026-02-12 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("file_path", models.CharField(max_length=1000)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                (
                    "classification_level",
                    models.IntegerField(
                        default=0,
                        help_text="0=Public, 1-5=Increasing restriction levels",
                    ),
                ),
                (
                    "visibility_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("restricted", "Restricted"),
                            ("private", "Private"),
                        ],
                        default="restricted",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("chunk_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.department",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("role", "Role"),
                            ("department", "Department"),
                            ("user", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "access_id",
                    models.UUIDField(help_text="UUID of the role, department, or user"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="documents.document",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_access",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "status"], name="documents_tenant__ebc015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "visibility_type"],
                name="documents_tenant__680e01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["department"], name="documents_departm_ec72b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by"], name="documents_uploade_aad805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["classification_level"], name="documents_classif_b82724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["document", "access_type", "access_id"],
                name="document_ac_documen_f7f20f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["access_type", "access_id"],
                name="document_ac_access__cc686f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentaccess",
            unique_together={("document", "access_type", "access_id")},
        ),
    ]
