# Generated by Django 5.0.1 on 2026-03-10 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_populate_org_units"),
        ("documents", "0001_initial"),
        ("rbac", "0004_populate_role_closure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentaccess",
            name="document_ac_documen_f7f20f_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentaccess",
            name="document_ac_access__cc686f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="documentaccess",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Time-bound access. Null = permanent.", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="include_descendants",
            field=models.BooleanField(
                default=True, help_text="For org_unit grants: include child units?"
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_grants",
                to="core.orgunit",
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_grants",
                to="rbac.role",
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_user_grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentaccess",
            name="access_id",
            field=models.UUIDField(
                blank=True, help_text="UUID of the role, department, or user", null=True
            ),
        ),
        migrations.AlterField(
            model_name="documentaccess",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("role", "Role"),
                    ("department", "Department"),
                    ("org_unit", "Org Unit"),
                    ("user", "User"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["document", "access_type"],
                name="document_ac_documen_b97932_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(fields=["role"], name="document_ac_role_id_2fd717_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["org_unit"], name="document_ac_org_uni_2ddbd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(fields=["user"], name="document_ac_user_id_aaf68e_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["expires_at"], name="document_ac_expires_4f0a36_idx"
            ),
        ),
    ]
