# Generated by Django 5.0.1 on 2026-03-11 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auth_identity_redesign"),
        ("documents", "0002_upgrade_document_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="author",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hex digest of the file content",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="file_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Storage key (e.g. tenant_id/YYYY/MM/sha256prefix/uuid.ext)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="document",
            name="mime_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_progress",
            field=models.IntegerField(
                default=0, help_text="0-100 percent of processing completed"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="retention_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Do not permanently delete before this date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="permission_level",
            field=models.CharField(
                choices=[("read", "Read"), ("write", "Write"), ("manage", "Manage")],
                default="read",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="documents.documentfolder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documentfolder",
            ),
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                (
                    "category",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Auto-classified")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_tags",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTagAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="documents.document",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="documents.documenttag",
                    ),
                ),
            ],
            options={
                "db_table": "document_tag_assignments",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("file_key", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=255)),
                (
                    "change_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.documentversion",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "is_deleted"], name="documents_tenant__953d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["folder"], name="documents_folder__5c7d69_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_hash"], name="documents_content_25403e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentfolder",
            unique_together={("tenant", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="documenttag",
            unique_together={("tenant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="documenttagassignment",
            unique_together={("document", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version_number")},
        ),
    ]
