# Generated by Django 5.0.1 on 2026-03-11 16:23

import os
import uuid

from django.conf import settings
from django.db import migrations


def backfill_documents(apps, schema_editor):
    """
    For every existing document that lacks a file_key:
     - derive file_key from the absolute file_path
     - create a DocumentVersion v1
     - link document.current_version to it
    """
    Document = apps.get_model('documents', 'Document')
    DocumentVersion = apps.get_model('documents', 'DocumentVersion')

    media_root = getattr(settings, 'MEDIA_ROOT', '')

    for doc in Document.objects.filter(file_key=''):
        if doc.file_path:
            # Derive file_key as relative path under MEDIA_ROOT
            if media_root and doc.file_path.startswith(media_root):
                rel = os.path.relpath(doc.file_path, media_root)
            else:
                rel = doc.file_path
            doc.file_key = rel

        # Populate original_filename from file_path if missing
        if not doc.original_filename and doc.file_path:
            doc.original_filename = os.path.basename(doc.file_path)

        doc.save(update_fields=['file_key', 'original_filename'])

        # Create v1 if none exists
        if not DocumentVersion.objects.filter(document=doc).exists():
            ver = DocumentVersion.objects.create(
                id=uuid.uuid4(),
                document=doc,
                version_number=1,
                file_key=doc.file_key,
                file_size=doc.file_size,
                content_hash=doc.content_hash,
                original_filename=doc.original_filename,
                mime_type=doc.mime_type,
                uploaded_by=doc.uploaded_by,
            )
            Document.objects.filter(pk=doc.pk).update(current_version=ver)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_management_upgrade"),
    ]

    operations = [
        migrations.RunPython(backfill_documents, migrations.RunPython.noop),
    ]
