# Generated by Django 5.0.1 on 2026-02-12 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                (
                    "vector_id",
                    models.CharField(
                        help_text="ID in Qdrant vector database",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "text_preview",
                    models.TextField(
                        blank=True,
                        help_text="First 500 chars of chunk text",
                        max_length=500,
                    ),
                ),
                ("token_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "vector_chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document"], name="vector_chun_documen_9f7d7a_idx"
                    ),
                    models.Index(
                        fields=["vector_id"], name="vector_chun_vector__fa446f_idx"
                    ),
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
