# Generated by Django 4.2.18 on 2026-02-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_subscriptionplan_tenantsubscription_systemauditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rag", "0002_chatsession_chatmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the folder", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_folders",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_folders",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional folder grouping for this chat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="rag.chatfolder",
            ),
        ),
        migrations.AddIndex(
            model_name="chatfolder",
            index=models.Index(
                fields=["tenant", "user"], name="chat_folder_tenant__7d0970_idx"
            ),
        ),
    ]
