# Generated by Django 4.2.18 on 2026-02-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_subscriptionplan_tenantsubscription_systemauditlog_and_more"),
        ("rag", "0003_chatfolder_chatsession_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatfolder",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_folders",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="core.tenant",
            ),
        ),
    ]
