apiVersion: v1
kind: Service
metadata:
  name: kodezera-backend
  labels:
    app: kodezera
spec:
  selector:
    app: kodezera
    component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
