apiVersion: v1
kind: Service
metadata:
  name: kodezera-postgres
  namespace: kodezera
  labels:
    app: kodezera
    component: postgres
spec:
  selector:
    app: kodezera
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
