apiVersion: v1
kind: Service
metadata:
  name: kodezera-qdrant
  namespace: kodezera
  labels:
    app: kodezera
    component: qdrant
spec:
  selector:
    app: kodezera
    component: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
  type: ClusterIP
