# Generated by Django 5.0.1 on 2026-03-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(
                default=False,
                help_text="System roles are auto-created and cannot be deleted.",
            ),
        ),
    ]
