# Generated by Django 5.0.1 on 2026-03-10 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_org_rbac_redesign"),
        ("rbac", "0002_role_is_system_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "role_closure",
            },
        ),
        migrations.AddField(
            model_name="permission",
            name="conditions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Optional ABAC conditions: {} = unrestricted, {"department": "own"} = own dept only.',
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="is_deny",
            field=models.BooleanField(
                default=False,
                help_text="If True, this permission DENIES rather than GRANTS. Deny always wins.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="max_users",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum users that can hold this role. Null = unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="priority",
            field=models.PositiveIntegerField(
                default=0, help_text="For conflict resolution — higher priority wins."
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="scope_org_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="If scope_type=org_unit, restricts this role to a subtree.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoped_roles",
                to="core.orgunit",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="scope_type",
            field=models.CharField(
                choices=[("global", "Global"), ("org_unit", "Org Unit")],
                default="global",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-expire this role assignment. Null = permanent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why this role was assigned.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("role", "Role"),
                    ("user", "User"),
                    ("department", "Department"),
                    ("org_unit", "Org Unit"),
                    ("audit_log", "Audit Log"),
                    ("tenant", "Tenant"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["is_deny"], name="permissions_is_deny_b2f63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["scope_type"], name="roles_scope_t_ccc0f7_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="user_roles_expires_aafda2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["is_active"], name="user_roles_is_acti_a67329_idx"
            ),
        ),
        migrations.AddField(
            model_name="roleclosure",
            name="ancestor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendant_role_links",
                to="rbac.role",
            ),
        ),
        migrations.AddField(
            model_name="roleclosure",
            name="descendant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ancestor_role_links",
                to="rbac.role",
            ),
        ),
        migrations.AddIndex(
            model_name="roleclosure",
            index=models.Index(
                fields=["ancestor", "depth"], name="role_closur_ancesto_2dd1fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleclosure",
            index=models.Index(
                fields=["descendant", "depth"], name="role_closur_descend_764ac5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roleclosure",
            unique_together={("ancestor", "descendant")},
        ),
    ]
