# Generated by Django 5.0.1 on 2026-03-13 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0017_auditretentionpolicy_compliancelog_auditevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("error_rate", "Error Rate (%)"),
                            ("avg_latency_ms", "Average Latency (ms)"),
                            ("queries_count", "Query Volume"),
                            ("tokens_used", "Tokens Used"),
                            ("active_users", "Active Users"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("gt", ">"), ("lt", "<"), ("gte", "≥"), ("lte", "≤")],
                        default="gt",
                        max_length=10,
                    ),
                ),
                ("threshold", models.FloatField()),
                (
                    "scope",
                    models.CharField(
                        choices=[("platform", "Platform"), ("tenant", "Tenant")],
                        default="tenant",
                        max_length=10,
                    ),
                ),
                ("notification_channels", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("cooldown_minutes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "alert_rules",
            },
        ),
        migrations.CreateModel(
            name="CostRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                (
                    "input_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                (
                    "output_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                (
                    "embedding_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cost_rates",
                "indexes": [
                    models.Index(
                        fields=["provider", "model", "-effective_from"],
                        name="cost_rates_provide_19c58d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_value", models.FloatField()),
                ("threshold_value", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_alerts",
                        to="analytics.alertrule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metric_alerts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "metric_alerts",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="metric_aler_tenant__a5675a_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="metric_aler_status_19687c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricHour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hour", models.DateTimeField(db_index=True)),
                ("queries_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("p95_latency_ms", models.FloatField(default=0.0)),
                ("active_users", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_hours",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "metric_hours",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-hour"],
                        name="metric_hour_tenant__ba339f_idx",
                    )
                ],
                "unique_together": {("tenant", "hour")},
            },
        ),
        migrations.CreateModel(
            name="MetricMonth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                ("queries_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("active_users", models.IntegerField(default=0)),
                ("storage_bytes", models.BigIntegerField(default=0)),
                ("documents_count", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "revenue_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_months",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "metric_months",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-month"],
                        name="metric_mont_tenant__b71169_idx",
                    )
                ],
                "unique_together": {("tenant", "month")},
            },
        ),
        migrations.CreateModel(
            name="QueryAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("latency_ms", models.IntegerField(default=0)),
                ("chunks_retrieved", models.IntegerField(default=0)),
                ("avg_relevance", models.FloatField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("is_follow_up", models.BooleanField(default=False)),
                ("is_failed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_analytics",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "query_analytics",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="query_analy_tenant__dc9b82_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="query_analy_user_id_1ecf74_idx",
                    ),
                ],
            },
        ),
    ]
